eno = int(input("Enter Employee Number"))
ename = input("Enter Employee Name")
esal = int(input("Enter Employee Salary"))
eaddr = input("Enter Employee Address")
married  = eval(input("Enter Employee Married ? [True/False]:"))

print("Please confirm your provided information")
print("Employee Number:", eno)
print("Employee Name:", ename)
print("Employee Salary:",esal)
print("Employee Address:" , eaddr)
print("Employee Married ?", married)